// netlify/functions/matesMorningNote.js
//
// READ-ONLY VERSION
// This function no longer generates any content.
// It only returns the note generated by the scheduled function:
//   generate-morning-note.js
//
// Key read:
//   matesMorningNote:au:YYYY-MM-DD
//
// If missing, returns a friendly placeholder.

const UPSTASH_URL = process.env.UPSTASH_REDIS_REST_URL;
const UPSTASH_TOKEN = process.env.UPSTASH_REDIS_REST_TOKEN;

// -------------------------------
// Redis getter
// -------------------------------
async function redisGet(key) {
  if (!UPSTASH_URL || !UPSTASH_TOKEN) return null;
  const res = await fetch(`${UPSTASH_URL}/get/${encodeURIComponent(key)}`, {
    headers: { Authorization: `Bearer ${UPSTASH_TOKEN}` }
  });
  if (!res.ok) return null;
  const data = await res.json().catch(() => null);
  return data && typeof data.result === "string" ? data.result : null;
}

// -------------------------------
// Helpers
// -------------------------------

// YYYY-MM-DD in Australia/Sydney
function getAussieDateString() {
  const now = new Date();
  const aussie = new Date(
    now.toLocaleString("en-US", { timeZone: "Australia/Sydney" })
  );
  const y = aussie.getFullYear();
  const m = String(aussie.getMonth() + 1).padStart(2, "0");
  const d = String(aussie.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

// -------------------------------
// MAIN HANDLER — read only
// -------------------------------
exports.handler = async function (event) {
  try {
    const region =
      (event.queryStringParameters && event.queryStringParameters.region) || "au";

    const todayAEST = getAussieDateString();
    const cacheKey = `matesMorningNote:${region}:${todayAEST}`;

    const cached = await redisGet(cacheKey);

    if (cached) {
      // Cached payload is already a JSON string
      return {
        statusCode: 200,
        headers: { "Content-Type": "application/json" },
        body: cached
      };
    }

    // If cache missing (scheduled function hasn’t run or failed)
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        region,
        note: "Today's morning note has not been generated yet.",
        generatedAt: null,
        _debug: {
          missingCache: true,
          cacheKey,
          message:
            "Scheduled function generate-morning-note has not yet written today's note."
        }
      })
    };

  } catch (err) {
    console.error("matesMorningNote handler error:", err);

    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        region: "unknown",
        note: "Unable to load today's note.",
        generatedAt: null,
        _debug: {
          error: err.message || String(err)
        }
      })
    };
  }
};
